### ISSUE TITLE
krew commands fail on fresh Windows install

### ISSUE THREAD

**Issue by kierenj** [kubernetes-sigs/krew#814]
Error message - e.g. for `kubectl krew search`:

````
failed to list indexes: failed to list the remote URL for index default: command execution failure, output="": exit status 1
Error: exit status 1
````

Output with `-v=5`:

````
I1121 09:39:10.965227 1140516 root.go:236] Ensure creating dir: "C:\\Users\\KierenJohnstone\\.krew"
I1121 09:39:10.965756 1140516 root.go:236] Ensure creating dir: "C:\\Users\\KierenJohnstone\\.krew\\store"
I1121 09:39:10.965756 1140516 root.go:236] Ensure creating dir: "C:\\Users\\KierenJohnstone\\.krew\\bin"
I1121 09:39:10.965756 1140516 root.go:236] Ensure creating dir: "C:\\Users\\KierenJohnstone\\.krew\\index"
I1121 09:39:10.965756 1140516 root.go:236] Ensure creating dir: "C:\\Users\\KierenJohnstone\\.krew\\receipts"
I1121 09:39:10.966277 1140516 root.go:130] skipping upgrade check
I1121 09:39:10.966277 1140516 migration.go:30] Checking if index migration is needed.
I1121 09:39:10.966277 1140516 migration.go:33] Index already migrated.
I1121 09:39:10.966277 1140516 root.go:165] detected windows, will check for old krew installations to clean up
I1121 09:39:10.967386 1140516 root.go:208] Clean up krew stale installations, current=v0.4.3
I1121 09:39:10.967386 1140516 install.go:257] Found 1 entries in krew store directory
I1121 09:39:10.967386 1140516 install.go:259] Found a krew installation: v0.4.3 (drwxrwxrwx)
I1121 09:39:10.967386 1140516 git.go:79] Going to run git config --get remote.origin.url
F1121 09:39:11.040841 1140516 root.go:78] exit status 1
command execution failure, output=""
sigs.k8s.io/krew/internal/gitutil.Exec
        /home/runner/work/krew/krew/internal/gitutil/git.go:89
sigs.k8s.io/krew/internal/gitutil.GetRemoteURL
        /home/runner/work/krew/krew/internal/gitutil/git.go:75
sigs.k8s.io/krew/internal/index/indexoperations.ListIndexes
        /home/runner/work/krew/krew/internal/index/indexoperations/index.go:50
sigs.k8s.io/krew/cmd/krew/cmd.glob..func4
        /home/runner/work/krew/krew/cmd/krew/cmd/search.go:47
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
sigs.k8s.io/krew/cmd/krew/cmd.Execute
        /home/runner/work/krew/krew/cmd/krew/cmd/root.go:76
main.main
        /home/runner/work/krew/krew/cmd/krew/main.go:25
runtime.main
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/proc.go:255
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
failed to list the remote URL for index default
sigs.k8s.io/krew/internal/index/indexoperations.ListIndexes
        /home/runner/work/krew/krew/internal/index/indexoperations/index.go:52
sigs.k8s.io/krew/cmd/krew/cmd.glob..func4
        /home/runner/work/krew/krew/cmd/krew/cmd/search.go:47
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
sigs.k8s.io/krew/cmd/krew/cmd.Execute
        /home/runner/work/krew/krew/cmd/krew/cmd/root.go:76
main.main
        /home/runner/work/krew/krew/cmd/krew/main.go:25
runtime.main
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/proc.go:255
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
failed to list indexes
sigs.k8s.io/krew/cmd/krew/cmd.glob..func4
        /home/runner/work/krew/krew/cmd/krew/cmd/search.go:49
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
sigs.k8s.io/krew/cmd/krew/cmd.Execute
        /home/runner/work/krew/krew/cmd/krew/cmd/root.go:76
main.main
        /home/runner/work/krew/krew/cmd/krew/main.go:25
runtime.main
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/proc.go:255
runtime.goexit
        /opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0x8a
k8s.io/klog/v2.(*loggingT).output(0xf3c880, 0x3, {0x0, 0x0}, 0xc00020ddc0, {0xc44a58, 0x1}, 0xc000284020, 0x0)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x569
k8s.io/klog/v2.(*loggingT).printf(0x0, 0xfce40ee8, {0x0, 0x0}, {0x0, 0x0}, {0xaa6c23, 0x3}, {0xc000284020, 0x1, ...})
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:751 +0x1d1
k8s.io/klog/v2.Fatalf(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1509
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
        /home/runner/work/krew/krew/cmd/krew/cmd/root.go:78 +0x155
main.main()
        /home/runner/work/krew/krew/cmd/krew/main.go:25 +0x3b

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x6a
created by k8s.io/klog/v2.init.0
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xfb
Error: exit status 255
````

My install steps:

1. Download krew.exe for latest release (just to Downloads folder)
2. Open admin command prompt (powershell)
3. Run `./krew install krew`
4. Add `$USERPROFILE%\.krew\bin` to path

**Comment by ahmetb** [comment]
Do you have git and does it work fine?

**Comment by kierenj** [comment]
Yes indeed it does. Is there a git command I can try to recreate? I tried it from various folders but had no issues. Although I note I didn't see any `.git` folders anywhere in `.krew`...

**Comment by mcollins-ttd** [comment]
I had to add an exception for the default index directory:

```
git config --global --add safe.directory C:/Users/foo/.krew/index/default
```

**Comment by wsmelton** [comment]
Setting safe directory has no effect on my system. Issue still persists.

**Comment by cgantert** [comment]
> I had to add an exception for the default index directory:
> 
> ```
> git config --global --add safe.directory C:/Users/foo/.krew/index/default
> ```

Solved the problem for me. Remember to replace "foo" with your own user name.
